# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: python3 app.py
  displayName: "Run Python App"

- script: |
    pip install selenium
    python3 selenium_test.py
  displayName: "Run Selenium Tests"
